name: Manual Trigger with Needs

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest   # ✅ runs-on inside the job
    steps:
      - name: Checkout code
        run: echo "Code clone from github"

  build:
    needs: [code]
    runs-on: ubuntu-latest   # ✅ runs-on inside every job
    steps:
      - name: Build Docker Container
        run: echo "Docker build"

  test:
    needs: [build]
    runs-on: ubuntu-latest   # ✅ runs-on inside every job
    steps:
      - name: Test Application
        run: echo "Docker build"
